version: "3.9"
services:
  fe:
    build:
      context: mf.fe/
      dockerfile: Dockerfile
    container_name: fe
    ports:
      - "3000:3000"
  
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/cond.d/nginx.conf
    depends_on:
      - fe
  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    # и снова мониторуем директорию nginx
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      # задаем переменные среды
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}    